-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Chimei Innolux Corporation 0x151E",
  mode = "1920x1080@60.00",
  position = "4536x616",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company LF24T35 HX5T101012",
  mode = "1920x1080@74.97",
  position = "1536x0",
  scale = 1,
  transform = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company LF24T35 HX5T101956",
  mode = "1920x1080@74.97",
  position = "2616x400",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Chimei Innolux Corporation 0x151E", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Chimei Innolux Corporation 0x151E" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Chimei Innolux Corporation 0x151E" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Samsung Electric Company LF24T35 HX5T101956", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:Samsung Electric Company LF24T35 HX5T101956" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Samsung Electric Company LF24T35 HX5T101956" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Chimei Innolux Corporation 0x151E", default = true })
hl.workspace_rule({ workspace = "21", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012", default = true })
hl.workspace_rule({ workspace = "22", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "23", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "24", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "31", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "32", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
hl.workspace_rule({ workspace = "33", monitor = "desc:Samsung Electric Company LF24T35 HX5T101012" })
