[window]
opacity = 0.7

[colors]
[colors.primary]
background = '#00060e'
foreground = '#d8eef8'

# Normal colors
[colors.normal]
black = '#00060e'
red = '#fee801'
green = '#39c4b6'
yellow = '#fee801'
blue = '#54c1e6'
magenta = '#9a9f17'
cyan = '#54c1e6'
white = '#d8eef8'

# Bright colors
[colors.bright]
black = '#071520'
red = '#fee801'
green = '#39c4b6'
yellow = '#fee801'
blue = '#54c1e6'
magenta = '#9a9f17'
cyan = '#54c1e6'
white = '#ffffff'

[colors.selection]
background = '#071520'
